# Generated by Django 4.2.4 on 2023-09-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, error_messages={'unique': 'Відправника вже було збережено раніше'}, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'sender',
                'verbose_name_plural': 'Senders',
            },
        ),
        migrations.CreateModel(
            name='SubscriberBuildNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_letter', models.CharField(choices=[(' ', ' '), ('A', 'А'), ('B', 'Б'), ('V', 'В'), ('G1', 'Г'), ('D', 'Д'), ('E1', 'Є'), ('E2', 'Е'), ('G2', 'Ж')], default=' ', max_length=2)),
                ('flat', models.CharField(blank=True, max_length=4)),
                ('street', models.CharField(choices=[('mkl', 'Мікльоша'), ('str', 'Стрийська'), ('sok', 'Сокільницька')], default='str', max_length=3)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_full_address', to='ukrposhta_example.subscriberbuildnumbermodel')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='SubscriberNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_name', to='ukrposhta_example.subscribermodel')),
            ],
            options={
                'verbose_name': 'subscriber name',
                'verbose_name_plural': 'Subscriber names',
            },
        ),
        migrations.CreateModel(
            name='LettersArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=13, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=13, unique=True)),
                ('date_of_storage_starting', models.DateField(blank=True, null=True)),
                ('repeat_delivery', models.BooleanField(blank=True, default=False, null=True)),
                ('is_court', models.BooleanField(blank=True, default=False)),
                ('is_court_subpoena', models.BooleanField(blank=True, default=False)),
                ('is_police', models.BooleanField(blank=True, default=False)),
                ('is_police_fine', models.BooleanField(blank=True, default=False)),
                ('is_letter_issued', models.BooleanField(blank=True, default=False)),
                ('is_returned', models.BooleanField(blank=True, default=False)),
                ('letter_image', models.ImageField(blank=True, default='letters/letter_image/default.png', null=True, upload_to='letters/letter_image/')),
                ('comments', models.TextField(blank=True)),
                ('recipient_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriber_letter', to='ukrposhta_example.subscribermodel')),
                ('sender_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_sender', to='ukrposhta_example.sendermodel')),
            ],
            options={
                'verbose_name': 'лист на збереженні',
                'verbose_name_plural': 'Листи на збереженні',
                'ordering': ['-id'],
            },
        ),
    ]
