# Generated by Django 4.2.4 on 2023-09-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ukrposhta_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(choices=[('mkl', 'Мікльоша'), ('str', 'Стрийська'), ('sok', 'Сокільницька')], default='str', max_length=3)),
                ('build', models.CharField(choices=[('', ''), ('3', '3'), ('5', '5'), ('7', '7'), ('9', '9'), ('11', '11'), ('13', '13'), ('15', '15'), ('17', '17'), ('20', '20'), ('23', '23'), ('25', '25'), ('27', '27'), ('73', '73'), ('75', '75'), ('77', '77'), ('79', '79'), ('81', '81'), ('85', '85'), ('87', '87'), ('89', '89'), ('91', '91'), ('93', '93'), ('99', '99'), ('101', '101'), ('103', '103'), ('105', '105'), ('107', '107'), ('111', '111'), ('113', '113'), ('115', '115'), ('117', '117'), ('123', '123'), ('127', '127'), ('129', '129'), ('133', '133'), ('260', '260'), ('262', '262'), ('264', '264'), ('266', '266'), ('268', '268'), ('270', '270'), ('272', '272'), ('274', '274'), ('276', '276'), ('278', '278'), ('280', '280'), ('282', '282'), ('284', '284'), ('286', '286'), ('288', '288'), ('290', '290'), ('292', '292'), ('294', '294'), ('296', '296'), ('298', '298'), ('300', '300'), ('302', '302'), ('304', '304'), ('306', '306'), ('308', '308'), ('310', '310'), ('312', '312'), ('314', '314'), ('316', '316'), ('318', '318'), ('320', '320'), ('322', '322'), ('324', '324'), ('326', '326'), ('328', '328'), ('330', '330')], default='', max_length=3)),
                ('build_letter', models.CharField(blank=True, choices=[('', ''), ('A', 'А'), ('B', 'Б'), ('V', 'В'), ('G1', 'Г'), ('D', 'Д'), ('E1', 'Є'), ('E2', 'Е'), ('G2', 'Ж')], default='', max_length=2)),
                ('flat', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'verbose_name': 'recipient',
                'verbose_name_plural': 'Recipient',
                'ordering': ['build'],
            },
        ),
        migrations.CreateModel(
            name='RecipientNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_name', to='ukrposhta_example.recipientmodel')),
            ],
            options={
                'verbose_name': 'subscriber name',
                'verbose_name_plural': 'Subscriber names',
            },
        ),
        migrations.RemoveField(
            model_name='subscribermodel',
            name='build',
        ),
        migrations.RemoveField(
            model_name='subscribernamemodel',
            name='address',
        ),
        migrations.AlterField(
            model_name='lettersarchivemodel',
            name='sender_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_letter', to='ukrposhta_example.sendermodel'),
        ),
        migrations.DeleteModel(
            name='SubscriberBuildNumberModel',
        ),
        migrations.DeleteModel(
            name='SubscriberNameModel',
        ),
        migrations.AlterField(
            model_name='lettersarchivemodel',
            name='recipient_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_letter', to='ukrposhta_example.recipientmodel'),
        ),
        migrations.DeleteModel(
            name='SubscriberModel',
        ),
    ]
